### ISSUE TITLE
Support for 1.27

### ISSUE THREAD

**Issue by sfarmani** [destroy/Manabars#1]
Hi! since 1.27 patch came out, are you going to add support for 1.27?

**Comment by Karaulov** [comment]
Possible get offsets from https://github.com/Karaulov/WarcraftIII_DLL_126-xxx :)

**Comment by sfarmani** [comment]
Oh cool did you recently update to 1.27? Also I have no idea what to do with the offsets ;/ is it possible for you to just compile the manabar file into a mixfile?
